name: sign_in
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #The following adds the Cupertino Icons font to your application.
  #Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  #To validate form
  form_validator: ^1.0.3
  #State management and dependecy injection
  flutter_riverpod: ^2.0.2
  firebase_core: ^2.1.0
  firebase_auth: ^4.0.2
  #Generate model easier and without boilerplate
  freezed_annotation: ^2.2.0
  #Animations
  lottie: ^1.4.2
  #Routing
  routemaster: ^1.0.1
  #Fonts
  google_fonts: ^3.0.1
  #Bottom Navigation
  curved_navigation_bar: ^1.0.3
  #Qr Scanner
  mobile_scanner: ^2.0.0
  #HTTP requests
  http: ^0.13.5
  #Interact with google sheets
  gsheets: ^0.4.2
  #Upload sounds for scanner notification
  audioplayers: ^1.1.1
  #To vibrate phone
  vibration: ^1.7.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  build_runner: ^2.3.2
  json_serializable: ^6.5.3
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0
  change_app_package_name: ^1.1.0

flutter_icons:
  ios: true
  android: true
  image_path: "assets/kpopland_launcher_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
